export const PLATFORM_NAME = 'Guinée Multiservices'
export const PLATFORM_TAGLINE = 'Une seule carte, tous vos services'
export const PLATFORM_LOGO = '/logo.png'
export const PLATFORM_FAVICON = '/favicon.png'
export const ADMIN_EMAIL = 'admin@mscarte.com'
export const SUPPORT_EMAIL = 'support@mscarte.com'
export const CLIENT_DASHBOARD_PATH = '/tableau-de-bord'
